// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for [`BACKEND_URL_DISCOVERED`].
 */
export type BackendUrlEvent = { id: string, url: string, };
