// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BackendService = { id: string, name: string, command: string, host: string | null, port: number | null, envFile: string | null, envVars: { [key: string]: string } | null, environment: string, autoStart: boolean, status: string, pid: number | null, url: string | null, error: string | null, workingDirectory: string | null, startedAt: string | null, };
