// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Extension = { package: string, version: string, install_method: string, channel: string, };
