// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GenerateCertArgs = { commonName: string, orgName: string, altNames: Array<string>, outputDir: string, daysValid: number, password: string | null, installInTrustStore: boolean, };
