// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for [`INSTALL_PROGRESS`].
 */
export type InstallProgressEvent = { 
/**
 * Phase identifier — `"download"`, `"install"`, `"config"`,
 * `"complete"`, `"error"`, `"abort"`. Connector decides the vocabulary.
 */
step: string, 
/**
 * 0.0–1.0.
 */
progress: number, 
/**
 * Human-readable status line.
 */
message: string, };
