// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Typed error returned by every command. Serializes as a tagged JSON
 * object so the renderer can match on `kind` instead of parsing strings.
 */
export type IpcError = { "kind": "not-implemented" } & string | { "kind": "io" } & string | { "kind": "invalid-argument" } & string | { "kind": "unauthorized" } & string | { "kind": "conflict" } & string | { "kind": "internal" } & string;
