// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for [`JUPYTER_STATUS_UPDATE`].
 */
export type JupyterStatusEvent = { environmentName: string, status: string, };
