// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LogEntry = { 
/**
 * Milliseconds since epoch.
 */
timestamp: bigint, content: string, process_id: string, };
