// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type McpSpec = { id: string, host: string, port: number, environment: string, 
/**
 * `"streamable-http"` (default) | `"sse"` | `"stdio"`.
 */
transport: string, authUsername: string | null, authPassword: string | null, 
/**
 * Optional allowlist of tools to expose. None = all.
 */
toolAllowlist: Array<string>, 
/**
 * Optional denylist.
 */
toolDenylist: Array<string>, workingDirectory: string | null, };
