// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type ObbCallArgs = { 
/**
 * The route, e.g. `/equity/price/historical` (with or without the
 * `/api/v1` prefix).
 */
route: string, 
/**
 * Query parameters. For data-processing routes that take POST,
 * `params.body` (if present) becomes the JSON body.
 */
params: { [key: string]: JsonValue } | null, 
/**
 * Method override. Defaults to GET.
 */
method: string | null, };
