// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for [`PROCESS_OUTPUT`].
 */
export type ProcessOutputEvent = { processId: string, output: string, 
/**
 * Milliseconds since epoch.
 */
timestamp: bigint, 
/**
 * `"stdout"`, `"stderr"`, or `"system"` (for synthesized banners).
 */
type: string, };
