// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Probe a provider's credentials by invoking a known cheap route.
 * The connector decides which route is "cheap" per provider; for the
 * generic implementation we let the caller specify.
 */
export type ProviderValidateArgs = { provider: string, probe_route: string, probe_params: { [key: string]: JsonValue } | null, };
