// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Free-text search over the route catalog (path + model + summary).
 */
export type RouteSearchArgs = { query: string, };
