// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Full route catalog, derived from `/openapi.json`. Each entry has the
 * path, the HTTP method, the data model name (`openapi_extra.model`),
 * and any tag/category.
 */
export type RouteInfo = { path: string, method: string, model: string | null, tags: Array<string>, summary: string | null, providers: Array<string>, };
