// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServerSpec = { id: string, host: string, port: number, 
/**
 * Conda env name or Python venv path. Connector decides which.
 */
environment: string, 
/**
 * Optional path to a `.env` file the server should source.
 */
envFile: string | null, 
/**
 * Extra env vars. Merged after `env_file`.
 */
envVars: { [key: string]: string }, 
/**
 * CLI args to append to `openbb-api`. E.g. `["--ssl-keyfile", "key.pem"]`.
 */
extraArgs: Array<string>, 
/**
 * Working directory for the spawned process.
 */
workingDirectory: string | null, };
